#  Copyright (c) 2021.  Ioannis E. Kommas. All Rights Reserved.
my_age = ...
half_my_age = ...
surname = ...
name = ...
name_and_surname = ...

print(f"""
Γειά σας, Ονομάζομαι {name_and_surname}, 
είμαι {my_age} ετών,
τα πρώτα {half_my_age} χρόνια της ζωής μου
ήταν ακριβώς τα μισά χρόνια της ευτυχίας μου.
""")


