#  Copyright (c) 2020. Ioannis E. Kommas. All Rights Reserved.
# ------------------- ΑΣΚΗΣΗ ---------------------
my_age = ...
half_my_age = ...
greeting = ...
name = ...
greeting_with_name = ...

print("""

""")